version: "2"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "http.host=0.0.0.0"
      - "transport.host=0.0.0.0"
      - "xpack.security.enabled=false"
      - "discovery.type=single-node"